services:
  app:
    image: 3olen-framework-my_app
    container_name: partiel-app
    build:
      context: ./docker/php
    volumes:
    - .:/usr/app
    networks:
    - partiel-network

  nginx:
    image: nginx
    depends_on:
    - app
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./public:/usr/app/public
    - ./var/log/nginx/:/usr/app/var/log/nginx/
    ports:
    - "8000:80"
    networks:
    - partiel-network

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pwd
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data:rw
    networks:
    - partiel-network

  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - "1080:1080"
    - "1025:1025"
    networks:
    - partiel-network

volumes:
  db_data:

networks:
  partiel-network:
